Allows to see ILM failures for hidden and system indices
elastic/support-diagnostics pull request #600
Opened 2022-07-28 19:33 UTC by lucabelluccini

The changes should allow to see ILM failures for system/hidden indices.

2022-08-01 16:35 UTC, jpcarey requested changes

2022-08-01 16:35 UTC, jpcarey commented on src/main/resources/elastic-rest.yml
> +    ">= 7.7.0": "/*/_ilm/explain?only_errors=true&human&pretty&expand_wildcards=all"
```suggestion
    ">= 7.4.0 < 7.7.0": "/*/_ilm/explain?only_errors=true&human&pretty"
    ">= 7.7.0": "/*/_ilm/explain?only_errors=true&human&pretty&expand_wildcards=all"
```

2022-08-01 16:35 UTC, jpcarey commented on src/main/resources/elastic-rest.yml
> +    ">= 7.7.0": "/*/_ilm/explain?human&pretty&expand_wildcards=all"
```suggestion
    ">= 6.6.0 < 7.7.0": "/*/_ilm/explain?human&pretty"
    ">= 7.7.0": "/*/_ilm/explain?human&pretty&expand_wildcards=all"
```

2022-09-01 11:28 UTC, lucabelluccini commented
Accepted the modifications (thank you for the fixes and review @jpcarey)!

2022-09-01 14:24 UTC, jpcarey approved these changes
LGTM. @lucabelluccini I didn't realize this was ready to re-review. It does not show up in my Github PR view unless it is awaiting review / re-review.

2022-09-01 14:24 UTC, merged